security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        my_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: /community/login
                check_path: /community/login
            logout:
                path:   /community/logout
                target: /
    access_control:
        - { path: ^/community/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/community/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/community/thankyou, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN