---
#--- STAGES ---------------------------------------------------------------------------------------
# build:      create docker images and dependencies
# test:       deploy staging environment to container host and run tests
# deploy:     deploy application to production
# teardown:   remove application (trigger: manual)
stages:
  - build
  - test
  - deploy
  - teardown


#--- JOBS -----------------------------------------------------------------------------------------

build:branch:
  stage: build
  image: docker
  before_script:
    - docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN $CI_REGISTRY 2>/dev/null
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  tags:
    - docker-executor

test:app:
  stage: test
#  image: $CI_REGISTRY/nevercodealone/docker-codeception:gitlab-ci-integrated
  image: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  services:
    - name: mariadb
      alias: database
    - name: selenium/standalone-chrome
      alias: selenium
  variables:
    APP_ENV: dev
    DATABASE_URL: mysql://nca:nca@database/nca
    DATABASE_HOST: database
    DATABASE_NAME: nca
    DATABASE_USER: nca
    DATABASE_PASS: nca
    MYSQL_DATABASE: nca
    MYSQL_PASSWORD: nca
    MYSQL_ROOT_PASSWORD: nca
    MYSQL_USER: nca
    WEBDRIVER_URL: selenium
    WEBSITE_URL: http://127.0.0.1
  before_script:
    # services don't know each other so we have to export their IP address
    # if they need to reach each other
    - export WEBSITE_IP=$(tail -n1 /etc/hosts | awk '{print $1}')
  script:
    - 'echo "APP_ENV: ${APP_ENV}"'
    - bin/console doctrine:schema:create
    - codecept build
    - codecept run -vvv --html
  artifacts:
    when: always
    paths:
      - tests/_output/*
  tags:
    - docker-executor

#deploy:staging:
#  stage: test
#  image: identt/rancher-compose
#  environment:
#    name: staging
#    url: "output.${CI_COMMIT_REF_SLUG}.${TRAEFIK_DOMAIN}"
#  variables:
#    CORS_ALLOW_ORIGIN: '^https?://(.*\.)?nevercodealone.de:?[0-9]*$$'
#    DATABASE_URL: mysql://nca:nca@database/nca
#    DATABASE_HOST: database
#    DATABASE_NAME: nca
#    DATABASE_USER: nca
#    DATABASE_PASS: nca
#    TRAEFIK_DOMAIN: "develop.nevercodealone.de"
#    TRAEFIK_URL: "${CI_COMMIT_REF_SLUG}.${TRAEFIK_DOMAIN}"
#    BROWSER_URL: "${CI_COMMIT_REF_SLUG}.${TRAEFIK_DOMAIN}"
#    OUTPUT_URL: "output.${CI_COMMIT_REF_SLUG}.${TRAEFIK_DOMAIN}"
#    WEBDRIVER_URL: selenium.stage.nevercodealone.de
#  script:
#    - rancher-compose -f docker-compose-ci.yml -p $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG rm -v -f
#    - rancher-compose -f docker-compose-ci.yml -p $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG up -d
#    - sleep 10
#    - curl -sSL "output.${CI_COMMIT_REF_SLUG}.${TRAEFIK_DOMAIN}/runtest"
#  tags:
#    - docker-executor
#  except:
#    - master

#teardown:
#  stage: teardown
#  image: identt/rancher-compose
#  script:
#    - rancher-compose -f docker-compose-ci.yml -p $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG rm -v -f
#  tags:
#    - docker-executor
#  when: manual

