#--- STAGES ---------------------------------------------------------------------------------------
# build:        create docker data image
# static_test:  run static tests in data container
# deploy:       deploy application to staging
# dynamic_test: test deployed staging environment
image: docker:latest

stages:
  - build

#--- JOBS -----------------------------------------------------------------------------------------
build:production:
  stage: build
  image: composer
  before_script:
    - composer selfupdate
  script:
    - composer install -d $CI_PROJECT_DIR --optimize-autoloader --no-dev
    - rm -rf .git
    - rm -rf .gitlabenv
  artifacts:
    paths:
    - $CI_PROJECT_DIR
    expire_in: 3 days
    when: on_success
  tags:
    - build
    - docker-executor
  only:
    - master

build:develop:
  stage: build
  image: composer
  before_script:
    - composer selfupdate
  script:
    - composer install -d $CI_PROJECT_DIR
    - rm -rf .git
    - rm -rf .gitlabenv
  artifacts:
    paths:
    - $CI_PROJECT_DIR
    expire_in: 3 days
    when: on_success
  tags:
    - build
    - docker-executor
  only:
    - develop
    - enable_ssh