---
version: '2'

services:
  db:
    environment:
    - MYSQL_DATABASE_FILE=/run/secrets/nca_database_name
    - MYSQL_PASSWORD_FILE=/run/secrets/nca_database_pass
    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/nca_database_root_pass
    - MYSQL_USER_FILE=/run/secrets/nca_database_user
    image: mariadb
    labels:
      io.rancher.container.pull_image: always
    restart: always
    secrets:
    - nca_database_name
    - nca_database_pass
    - nca_database_root_pass
    - nca_database_user
    volumes:
    - db_data:/var/lib/mysql

  web:
    depends_on:
    - db
    environment:
    - APP_DEBUG_FILE=/run/secrets/nca_app_debug
    - APP_ENV_FILE=/run/secrets/nca_app_env
    - APP_SECRET_FILE=/run/secrets/nca_app_secret
    - CORS_ALLOW_ORIGIN_FILE=/run/secrets/nca_cors_allow_origin
    - DATABASE_URL_FILE=/run/secrets/nca_database_url
    image: $WEB_IMAGE
    labels:
      io.rancher.container.pull_image: always
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: 'Host:$HTTP_URL'
      traefik.frontend.entryPoints: http,https
      traefik.port: 80
    restart: always
    secrets:
    - nca_app_debug
    - nca_app_env
    - nca_app_secret
    - nca_cors_allow_origin
    - nca_database_url

volumes:
  db_data:

secrets:
  nca_database_name:
    external: true
  nca_database_pass:
    external: true
  nca_database_root_pass:
    external: true
  nca_database_user:
    external: true
  nca_app_debug:
    external: true
  nca_app_env:
    external: true
  nca_app_secret:
    external: true
  nca_cors_allow_origin:
    external: true
  nca_database_url:
    external: true

