---
version: '3.2'
services:

  # website
  server:
    image: registry.nevercodealone.de/nevercodealone/nevercodealone
    environment:
      DATABASE_URL: mysql://nca:nca@db/nca
    ports:
      - '8080:80'
    volumes:
      - application:/var/www/symfony
    depends_on:
      - db
    restart: always

  # database
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: nca
      MYSQL_PASSWORD: nca
      MYSQL_ROOT_PASSWORD: nca
      MYSQL_USER: nca
    restart: always

  # selenium container
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - '/dev/shm:/dev/shm'

  # codeception
  codeception:
    image: registry.nevercodealone.de/nevercodealone/docker-codeception
    environment:
      BROWSER_URL: http://server
      DB_HOST: db
      DB_NAME: nca
      DB_USER: nca
      DB_PASS: nca
      WEBDRIVER_URL: selenium
    command: tail -f /dev/null
    ports:
      - '8081:80'
    volumes:
      - application:/project
    depends_on:
      - server
      - db
      - selenium
    restart: always

volumes:
  application:

