---
version: '2'

services:
  webserver:
    image: $WEBSERVER_IMAGE
    environment:
      APP_ENV: $APP_ENV
      APP_SECRET: $APP_SECRET
      DATABASE_URL: mysql://$DB_USER:$DB_PASS@db/$DB_NAME
      CORS_ALLOW_ORIGIN: $CORS_ALLOW_ORIGIN
    volumes:
      - 'application:/var/www/html'
    restart: always
    labels:
      io.rancher.container.pull_image: always
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: 'Host:$HTTP_URL'
      traefik.frontend.entryPoints: http,https
      traefik.port: 80

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_USER: $DB_USER
    restart: always
    labels:
      io.rancher.container.pull_image: always

  toolbox:
    image: registry.nevercodealone.de/nevercodealone/docker-toolbox
    environment:
      CODECEPT_DATABASE_URL: mysql://$DB_USER:$DB_PASS@db/$DB_NAME
      CODECEPT_DB_HOST: db
      CODECEPT_DB_NAME: $DB_NAME
      CODECEPT_DB_PASS: $DB_PASS
      CODECEPT_DB_USER: $DB_USER
      CODECEPT_WEBDRIVER_URL: $WEBDRIVER_URL
      CODECEPT_WEBSITE_URL: $HTTP_URL
    volumes:
      - 'application:/home/www-data/symfony'
    ports:
      - 22
    depends_on:
      - webserver
    restart: always
    labels:
      io.rancher.container.pull_image: always

volumes:
  application:

