---
version: '2'

services:

  webserver:
    image: $WEBSERVER_IMAGE
    environment:
      SYMFONY_APP_ENV: $APP_ENV
      SYMFONY_APP_SECRET: $APP_SECRET
      SYMFONY_DATABASE_URL: mysql://$DB_USER:$DB_PASS@db/$DB_NAME
      SYMFONY_CORS_ALLOW_ORIGIN: $CORS_ALLOW_ORIGIN
    restart: always
    labels:
      io.rancher.container.pull_image: always
      # traefik.acme: true
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.entryPoints: http,https
      traefik.frontend.passHostHeader: true
      # traefik.frontend.redirect.entryPoint: https
      traefik.frontend.rule: 'Host:$HTTP_URL'
      traefik.port: 80

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_USER: $DB_USER
    restart: always
    labels:
      io.rancher.container.pull_image: always

