---
version: '2'
services:
  server:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
    environment:
      APP_ENV: $APP_ENV
      APP_SECRET: $APP_SECRET
      CORS_ALLOW_ORIGIN: $CORS_ALLOW_ORIGIN
      DATABASE_URL: $DATABASE_URL
      WEBDRIVER_URL: $WEBDRIVER_URL
    volumes:
      - application:/var/www/symfony
    labels:
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.domain: $TRAEFIK_DOMAIN
      traefik.frontend.rule: "Host:${TRAEFIK_URL}"
      traefik.port: 80
    links:
      - db
    depends_on:
      - db
    restart: always
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_PASSWORD: $DATABASE_PASS
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_USER: $DATABASE_USER
    labels:
      io.rancher.container.pull_image: always
    restart: always
  codeception:
    image: $CI_REGISTRY/nevercodealone/docker-codeception:curl-errors
    environment:
      BROWSER_URL: $BROWSER_URL
      DB_HOST: $DATABASE_HOST
      DB_NAME: $DATABASE_NAME
      DB_USER: $DATABASE_USER
      DB_PASS: $DATABASE_PASS
      WEBDRIVER_URL: $WEBDRIVER_URL
    volumes:
      - application:/project
    labels:
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.domain: $TRAEFIK_DOMAIN
      traefik.frontend.rule: "Host:${OUTPUT_URL}"
      traefik.port: 80
    links:
      - db
    depends_on:
      - server
      - db
    restart: always

volumes:
  application:

