version: '2'
services:
  # website
  server:
    image: $DOCKER_IMAGE
    environment:
      DATABASE_URL: mysql://$DB_USER:$DB_PASS@db/$DB_NAME
      CORS_ALLOW_ORIGIN: '^https?://(.*\.)?nevercodealone.de:?[0-9]*$$'
    volumes:
      - application:/var/www/symfony
    restart: always
    labels:
      io.rancher.container.pull_image: always
      traefik.acme: true
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.entryPoints: http,https
      traefik.frontend.passHostHeader: true
      # traefik.frontend.redirect.entryPoint: https
      traefik.frontend.rule: 'Host:${TRAEFIK_URL}'
      traefik.port: 80
  # database
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER
    restart: always
    labels:
      io.rancher.container.pull_image: always
  # toolbox
  toolbox:
    image: registry.nevercodealone.de/nevercodealone/docker-toolbox:next
    environment:
      CODECEPT_DB_HOST: db
      CODECEPT_DB_NAME: $DB_NAME
      CODECEPT_DB_PASS: $DB_PASS
      CODECEPT_DB_USER: $DB_USER
      CODECEPT_WEBDRIVER_URL: $WEBDRIVER_URL
      CODECEPT_WEBSITE_URL: $WEBSITE_URL
    volumes:
      - application:/home/www-data/symfony
    ports:
      - 22
    restart: always
    labels:
      io.rancher.container.pull_image: always
volumes:
  application:

