---
version: '2'

services:
  toolbox:
    image: $TOOLBOX_IMAGE
    environment:
      CODECEPT_DATABASE_URL: mysql://$DB_USER:$DB_PASS@db/$DB_NAME
      CODECEPT_DB_HOST: db
      CODECEPT_DB_NAME: nca
      CODECEPT_DB_PASS: nca
      CODECEPT_DB_USER: nca
      CODECEPT_WEBDRIVER_URL: $WEBDRIVER_URL
      CODECEPT_WEBSITE_URL: $HTTP_URL
    ports:
      - 22
    restart: always
    labels:
      io.rancher.container.pull_image: always

