---
version: '3.2'
services:

  # website
  server:
    image: registry.nevercodealone.de/nevercodealone/nevercodealone
    environment:
      CORS_ALLOW_ORIGIN: '^https?://(.*\.)?server:?[0-9]*$$'
      DATABASE_URL: mysql://nca:nca@db/nca
    ports:
      - '8080:80'
    volumes:
      - application:/var/www/symfony
    depends_on:
      - db
    restart: always

  # database
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: nca
      MYSQL_PASSWORD: nca
      MYSQL_ROOT_PASSWORD: nca
      MYSQL_USER: nca
    restart: always

  # selenium container
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  hub:
    image: selenium/hub

  # codeception
  codeception:
    image: registry.nevercodealone.de/nevercodealone/docker-codeception
    environment:
      BROWSER_URL: http://server
      DB_HOST: db
      DB_NAME: nca
      DB_USER: nca
      DB_PASS: nca
      WEBDRIVER_URL: hub
    ports:
      - '8081:80'
    volumes:
      - application:/project
    depends_on:
      - server
      - db
      - hub
    restart: always

volumes:
  application:

