---
version: '2'

services:
  db:
    environment:
    - MYSQL_DATABASE
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
    - MYSQL_USER
    image: mariadb
    labels:
      io.rancher.container.pull_image: always
    ports:
    - 3306/tcp
    restart: always

  web:
    depends_on:
    - db
    environment:
    - APP_DEBUG
    - APP_ENV
    - APP_SECRET
    - GOOGLE_API_KEY
    - CORS_ALLOW_ORIGIN
    - DATABASE_URL
    - MAIL_USER
    - MAIL_PASS
    - MAIL_HUB
    - MAIL_USER_FILE=/run/secrets/nca_mail_user
    - MAIL_PASS_FILE=/run/secrets/nca_mail_pass
    - MAIL_HUB_FILE=/run/secrets/nca_mail_hub
    - GOOGLE_API_KEY_FILE=/run/secrets/GOOGLE_API_KEY
    image: $WEB_IMAGE
    labels:
      io.rancher.container.pull_image: always
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: 'Host:$HTTP_URL,$WWW_URL'
      traefik.frontend.entryPoints: http,https
      traefik.port: 80
    restart: always
    secrets:
    - nca_mail_user
    - nca_mail_pass
    - nca_mail_hub
    - GOOGLE_API_KEY

secrets:
  nca_mail_user:
    external: true
  nca_mail_pass:
    external: true
  nca_mail_hub:
    external: true
  GOOGLE_API_KEY:
    external: true

