---
version: '3.2'
services:
  server:
    image: registry.nevercodealone.de/nevercodealone/nevercodealone
    environment:
      APP_ENV: dev
      APP_SECRET: insecure
      BROWSER_URL: http://server
      CORS_ALLOW_ORIGIN: '^https?://(.*\.)?server:?[0-9]*$$'
      DATABASE_URL: mysql://nca:nca@db/nca
      DB_HOST: db
      DB_NAME: nca
      DB_USER: nca
      DB_PASS: nca
      WEBDRIVER_URL: hub
    ports:
      - 8080:80
    restart: always

  # database
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: nca
      MYSQL_PASSWORD: nca
      MYSQL_ROOT_PASSWORD: nca
      MYSQL_USER: nca
    restart: always

  # selenium container
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  hub:
    image: selenium/hub

