version: '2'
services:
  # website
  server:
    image: registry.nevercodealone.de/nevercodealone/nevercodealone
    environment:
      DATABASE_URL: mysql://nca:nca@db/nca
    volumes:
      - application:/var/www/symfony
    restart: always
    labels:
      traefik.domain: develop.nevercodealone.de,
      traefik.enable: true,
      traefik.port: 80,
      traefik.docker.network: proxy,
      traefik.frontend.redirect.entryPoint: https,
      traefik.frontend.passHostHeader: true,
      traefik.acme: true,
      traefik.frontend.entryPoints: http,https
  # database
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: nca
      MYSQL_PASSWORD: nca
      MYSQL_ROOT_PASSWORD: nca
      MYSQL_USER: nca
    restart: always
  # toolbox
  toolbox:
    image: registry.nevercodealone.de/nevercodealone/docker-toolbox
    command: tail -f /dev/null
    volumes:
      - application:/project
    restart: always
volumes:
  application: