---
version: '3.6'

services:
  adminer:
    depends_on:
    - db
    image: adminer
    ports:
    - 8081:8080/tcp

  db:
    environment:
    - MYSQL_DATABASE
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
    - MYSQL_USER
    image: mariadb
    ports:
    - 33006:3306/tcp
    restart: always

  web:
    build:
      context: .
      target: webserver-local
    depends_on:
    - db
    environment:
    - APP_DEBUG
    - APP_ENV
    - APP_SECRET
    - CORS_ALLOW_ORIGIN
    - DATABASE_URL
    ports:
    - 8080:80/tcp
    restart: always

