---
version: '3.2'
services:
  server:
    image: registry.nevercodealone.de/nevercodealone/docker_composer_mysql
    volumes:
        - '.:/var/www/symfony'
    restart: always
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: nca
      MYSQL_PASSWORD: nca
      MYSQL_ROOT_PASSWORD: nca
      MYSQL_USER: nca
    restart: always

