---
version: '2'
services:
  server:
    image: nginx
    environment:
      APP_ENV: $APP_ENV
      APP_SECRET: $APP_SECRET
      CORS_ALLOW_ORIGIN: '^https?://(.*\.)?nevercodealone.de:?[0-9]*$$'
    volumes:
      - ./tests/_output:/usr/share/nginx/html
    labels:
      io.rancher.container.pull_image: always
      traefik.frontend.rule: 'Host:${TRAEFIK_URL}'
      traefik.domain: '${TRAEFIK_DOMAIN}'
      traefik.enable: 'true'
      traefik.port: '80'
    restart: always

