version: '2.1'

services:

  phpfpm:
    build: phpfpm/
    volumes:
      - "../../../:/app"
    environment:
      - PHP_IDE_CONFIG=serverName=nevercodealone
      - XDEBUG_CONFIG=remote_host=g082

  nginx:
    image: registry.nevercodealone.de/nevercodealone/docker_nginx:0.0.1
    volumes_from:
      - phpfpm
    volumes:
      - ./nginx/nevercodealone.nginx.conf:/etc/nginx/nevercodealone.nginx.conf
    ports:
      - "80:80"
    depends_on:
      - phpfpm

  mysql:
    build: mysql/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecure
      - MYSQL_DATABASE=sendis_dev
      - MYSQL_USER=sendis_dev_user
      - MYSQL_PASSWORD=sendis_dev_password

  memcached:
    image: memcached:1.5
